### ISSUE TITLE
Installation dependencies

### ISSUE THREAD

**Issue by garantjm** [jpsglouzon/structurexplor#1]
Note that 
Installation of "devtools" package have a dependance with "libcurl4-openssl-dev" from the system (Debian)

rCharts is not available from CRAN, use devtools to install it:
> require(devtools)
> install_github('ramnathv/rCharts')

BiocGenerics and Biostrings are available to install through Bioconductor:
> source("https://bioconductor.org/biocLite.R")
> biocLite(c("BiocGenerics", "Biostrings"))

**Comment by jpsglouzon** [comment]
Correct. I will update the README following your recommandation.  
Thanks
